# Generated by Django 2.2 on 2020-04-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('mobile_num', models.IntegerField(max_length=10)),
                ('emp_code', models.CharField(max_length=2)),
                ('position', models.CharField(choices=[('jdev', 'Jr.Developer'), ('sdev', 'Sr.Developer')], max_length=20)),
            ],
        ),
    ]
